services:
  postgres:
    image: postgres:15
    container_name: boilerplate-postgres-dev
    environment:
      POSTGRES_USER: boilerplate
      POSTGRES_PASSWORD: boilerplate
      POSTGRES_DB: boilerplate-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

  postgres-test:
    image: postgres:15
    container_name: boilerplate-postgres-test
    environment:
      POSTGRES_USER: boilerplate
      POSTGRES_PASSWORD: boilerplate
      POSTGRES_DB: boilerplate_test_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

volumes:
  postgres_dev_data:
  postgres_test_data: